# Site settings
title: danielsabbagh.com
email: dsabbagh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is my effort at tracking my professional growth as a 
  software developer. I'm interested in the software testing, web side
  of things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "danielSabbagh.com" # the base hostname & protocol for your site
github_username:  dsab123
resume:	          resume

# Build settings
markdown: kramdown
